// This file was autogenerated by create-env.js

export namespace Host {
	export type uint32 = u32;
	export type uint64 = u64;

	// @ts-ignore decorators are valid here
	@external("suffiks", "AddEnv")
	export declare function addEnv(ptr : uint32, size : uint32): void;
	// @ts-ignore decorators are valid here
	@external("suffiks", "AddEnvFrom")
	export declare function addEnvFrom(ptr : uint32, size : uint32): void;
	// @ts-ignore decorators are valid here
	@external("suffiks", "AddLabel")
	export declare function addLabel(ptr : uint32, size : uint32): void;
	// @ts-ignore decorators are valid here
	@external("suffiks", "AddAnnotation")
	export declare function addAnnotation(ptr : uint32, size : uint32): void;
	// @ts-ignore decorators are valid here
	@external("suffiks", "AddInitContainer")
	export declare function addInitContainer(ptr : uint32, size : uint32): void;
	// @ts-ignore decorators are valid here
	@external("suffiks", "AddSidecar")
	export declare function addSidecar(ptr : uint32, size : uint32): void;
	// @ts-ignore decorators are valid here
	@external("suffiks", "MergePatch")
	export declare function mergePatch(ptr : uint32, size : uint32): void;
	// @ts-ignore decorators are valid here
	@external("suffiks", "ValidationError")
	export declare function validationError(ptr : uint32, size : uint32): void;
	// @ts-ignore decorators are valid here
	@external("suffiks", "GetOwner")
	export declare function getOwner(): uint64;
	// @ts-ignore decorators are valid here
	@external("suffiks", "GetSpec")
	export declare function getSpec(): uint64;
	// @ts-ignore decorators are valid here
	@external("suffiks", "GetOld")
	export declare function getOld(): uint64;
	// @ts-ignore decorators are valid here
	@external("suffiks", "CreateResource")
	export declare function createResource(gvrPtr : uint32, gvrSize : uint32, specPtr : uint32, specSize : uint32): uint64;
	// @ts-ignore decorators are valid here
	@external("suffiks", "UpdateResource")
	export declare function updateResource(gvrPtr : uint32, gvrSize : uint32, specPtr : uint32, specSize : uint32): uint64;
	// @ts-ignore decorators are valid here
	@external("suffiks", "DeleteResource")
	export declare function deleteResource(gvrPtr : uint32, gvrSize : uint32, namePtr : uint32, nameSize : uint32): uint64;
	// @ts-ignore decorators are valid here
	@external("suffiks", "GetResource")
	export declare function getResource(gvrPtr : uint32, gvrSize : uint32, namePtr : uint32, nameSize : uint32): uint64;
}
