// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v3.20.1

import { Writer, Reader } from "as-proto/assembly";

export class VolumeMount {
  static encode(message: VolumeMount, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.name);

    writer.uint32(16);
    writer.bool(message.readOnly);

    writer.uint32(26);
    writer.string(message.mountPath);

    writer.uint32(34);
    writer.string(message.subPath);
  }

  static decode(reader: Reader, length: i32): VolumeMount {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new VolumeMount();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.name = reader.string();
          break;

        case 2:
          message.readOnly = reader.bool();
          break;

        case 3:
          message.mountPath = reader.string();
          break;

        case 4:
          message.subPath = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  name: string;
  readOnly: bool;
  mountPath: string;
  subPath: string;

  constructor(
    name: string = "",
    readOnly: bool = false,
    mountPath: string = "",
    subPath: string = ""
  ) {
    this.name = name;
    this.readOnly = readOnly;
    this.mountPath = mountPath;
    this.subPath = subPath;
  }
}
